"""Python emitter that turns validated wren schema into python source code"""

from __future__ import annotations

from .ast import ArrayType, PrimitiveType, Schema, Struct, StructType, Type
from .typemap import PRIMITIVES

_HEADER = """\
# Generated by wrengen. Do not edit.
from __future__ import annotations

from dataclasses import dataclass

from wren.codec import Reader, Writer
"""

def _py_type(t: Type) -> str:
    if isinstance(t, PrimitiveType):
        return PRIMITIVES[t.name].py_type
    if isinstance(t, StructType):
        return t.name
    return f"list[{_py_type(t.element)}]"

def _encode_lines(t: Type, expr: str, depth: int) -> list[str]:
    if isinstance(t, PrimitiveType):
        if t.name == "bytes":
            return [f"w.put_bytes({expr})"]
        if t.name == "string":
            return [f"w.put_string({expr})"]
        return [f'w.put("{PRIMITIVES[t.name].py_fmt}", {expr})']
    if isinstance(t, StructType):
        return [f"{expr}._encode(w)"]

    # arraytype
    item = f"_e{depth}"
    if t.size is None:
        lines = [f'w.put("I", len({expr}))']
    else:
        lines = [
            f"if len({expr}) != {t.size}:",
            f'    raise ValueError(f"expected {t.size} elements, got {{len({expr})}}")',
        ]
    lines.append(f"for {item} in {expr}:")
    lines += ["    " + line for line in _encode_lines(t.element, item, depth + 1)]
    return lines

def _decode_expr(t: Type) -> str:
    if isinstance(t, PrimitiveType):
        if t.name == "bytes":
            return "r.get_bytes()"
        if t.name == "string":
            return "r.get_string()"
        return f'r.get("{PRIMITIVES[t.name].py_fmt}")'
    if isinstance(t, StructType):
        return f"{t.name}._decode(r)"

    count = 'r.get("I")' if t.size is None else str(t.size)
    return f"[{_decode_expr(t.element)} for _ in range({count})]"

def _emit_struct(s: Struct) -> list[str]:
    lines = ["@dataclass", f"class {s.name}:"]
    lines += [f"    {f.name}: {_py_type(f.type)}" for f in s.fields]

    lines += ["", "    def _encode(self, w: Writer) -> None:"]
    body = [line for f in s.fields
            for line in _encode_lines(f.type, f"self.{f.name}", 0)]
    lines += ["        " + line for line in body] or ["        pass"]

    lines += ["", "    @classmethod", f"    def _decode(cls, r: Reader) -> {s.name}:"]
    if s.fields:
        lines.append("        return cls(")
        lines += [f"            {_decode_expr(f.type)}," for f in s.fields]
        lines.append("        )")
    else:
        lines.append("        return cls()")

    lines += [
        "",
        "    def encode(self) -> bytes:",
        "        w = Writer()",
        "        self._encode(w)",
        "        return w.getvalue()",
        "",
        "    @classmethod",
        f"    def decode(cls, data: bytes) -> {s.name}:",
        "        r = Reader(data)",
        "        value = cls._decode(r)",
        "        r.expect_end()",
        "        return value",
    ]
    return lines


def emit_python(schema: Schema) -> str:
    parts = [_HEADER]
    for s in schema.structs:
        parts.append("\n\n" + "\n".join(_emit_struct(s)) + "\n")
    return "".join(parts)