"""C emitter that turns validated wren schema into a c header and source file"""

from __future__ import annotations

from .ast import ArrayType, PrimitiveType, Schema, Struct, StructType, Type
from .typemap import PRIMITIVES

_BANNER = "// Generated by wrengen. Do not edit."

def _mangle(t: Type) -> str:
    if isinstance(t, PrimitiveType):
        return t.name
    if isinstance(t, StructType):
        return "S" + t.name
    if t.size is None:
        return "list_" + _mangle(t.element)
    return f"arr{t.size}_" + _mangle(t.element)

def _list_name(t: ArrayType) -> str:
    return "wren_" + _mangle(t)

def _decl(t: Type, name: str) -> str:
    if isinstance(t, PrimitiveType):
        return f"{PRIMITIVES[t.name].c_type} {name}"
    if isinstance(t, StructType):
        return f"{t.name} {name}"
    if t.size is None:
        return f"{_list_name(t)} {name}"
    inner = f"({name})" if name.startswith("*") else name
    return _decl(t.element, f"{inner}[{t.size}]")

def _lists_in(t: Type, out: dict[str, ArrayType]) -> None:
    if isinstance(t, ArrayType):
        _lists_in(t.element, out)
        if t.size is None:
            out.setdefault(_mangle(t), t)

def _min_size(t: Type, structs: dict[str, Struct]) -> int:
    if isinstance(t, PrimitiveType):
        size = PRIMITIVES[t.name].size
        return 4 if size is None else size
    if isinstance(t, StructType):
        return sum(_min_size(f.type, structs) for f in structs[t.name].fields)
    return 4 if t.size is None else t.size * _min_size(t.element, structs)

def _block(lines: list[str]) -> list[str]:
    return ["    " + line for line in lines]

def _encode_lines(t: Type, expr: str, depth: int) -> list[str]:
    if isinstance(t, PrimitiveType):
        fn = "bytes" if t.name in ("bytes", "string") else t.name
        return [f"wren_write_{fn}(w, {expr});"]
    if isinstance(t, StructType):
        return [f"{t.name}_encode(w, &{expr});"]
    i = f"i{depth}"
    if t.size is None:
        head = [f"wren_write_u32(w, {expr}.len);"]
        count, items = f"{expr}.len", f"{expr}.items"
    else:
        head, count, items = [], str(t.size), expr
    return head + [
        f"for (uint32_t {i} = 0; {i} < {count}; {i}++) {{",
        *_block(_encode_lines(t.element, f"{items}[{i}]", depth + 1)),
        "}",
    ]

def _decode_lines(t: Type, expr: str, depth: int,
                  structs: dict[str, Struct]) -> list[str]:
    if isinstance(t, PrimitiveType):
        fn = "bytes" if t.name in ("bytes", "string") else t.name
        return [f"wren_read_{fn}(r, &{expr});"]
    if isinstance(t, StructType):
        return [f"{t.name}_decode(r, a, &{expr});"]
    i = f"i{depth}"
    if t.size is None:
        head = [
            f"wren_read_count(r, {_min_size(t.element, structs)}, &{expr}.len);",
            f"{expr}.items = wren_read_alloc(r, a, {expr}.len, sizeof(*{expr}.items));",
        ]
        count, items = f"{expr}.len", f"{expr}.items"
    else:
        head, count, items = [], str(t.size), expr
    return head + [
        f"for (uint32_t {i} = 0; r->ok && {i} < {count}; {i}++) {{",
        *_block(_decode_lines(t.element, f"{items}[{i}]", depth + 1, structs)),
        "}",
    ]

def _struct_typedef(s: Struct) -> list[str]:
    body = [_decl(f.type, f.name) + ";" for f in s.fields]
    if not body:
        body = ["char _unused;  /* ISO C forbids empty structs */"]
    return [f"typedef struct {s.name} {{", *_block(body), f"}} {s.name};"]

def _prototypes(s: Struct) -> list[str]:
    return [
        f"void {s.name}_encode(wren_writer_t *w, const {s.name} *v);",
        f"void {s.name}_decode(wren_reader_t *r, wren_arena_t *a, {s.name} *out);",
    ]

def _struct_functions(s: Struct, structs: dict[str, Struct]) -> list[str]:
    enc = [line for f in s.fields
           for line in _encode_lines(f.type, f"v->{f.name}", 0)]
    dec = [line for f in s.fields
           for line in _decode_lines(f.type, f"out->{f.name}", 0, structs)]
    enc_unused = [] if s.fields else ["(void)w;", "(void)v;"]
    dec_unused = ["(void)a;"] + ([] if s.fields else ["(void)r;", "(void)out;"])
    return [
        f"void {s.name}_encode(wren_writer_t *w, const {s.name} *v) {{",
        *_block(enc_unused + enc),
        "}",
        "",
        f"void {s.name}_decode(wren_reader_t *r, wren_arena_t *a, {s.name} *out) {{",
        *_block(dec_unused + dec),
        "}",
    ]

def emit_c(schema: Schema, name: str) -> tuple[str, str]:
    structs = {s.name: s for s in schema.structs}

    h = [_BANNER, "#pragma once", "",
         "#include <stdbool.h>", "#include <stdint.h>", "",
         '#include "wren/codec.h"']
    emitted: set[str] = set()
    for s in schema.structs:
        needed: dict[str, ArrayType] = {}
        for f in s.fields:
            _lists_in(f.type, needed)
        for key, t in needed.items():
            if key in emitted:
                continue
            emitted.add(key)
            h += ["", "typedef struct {", "    uint32_t len;",
                  f"    {_decl(t.element, '*items')};",
                  f"}} {_list_name(t)};"]
        h += ["", *_struct_typedef(s), "", *_prototypes(s)]

    c = [_BANNER, f'#include "{name}.h"']
    for s in schema.structs:
        c += ["", *_struct_functions(s, structs)]

    return "\n".join(h) + "\n", "\n".join(c) + "\n"