"""C emitter that turns validated wren schema into a c header and source file"""

from __future__ import annotations

from .ast import (
    ArrayType, Method, PrimitiveType, Schema, Service, Struct, StructType,
    TupleReturn, Type,
)
from .typemap import PRIMITIVES

_BANNER = "// Generated by wrengen. Do not edit."

def _mangle(t: Type) -> str:
    if isinstance(t, PrimitiveType):
        return t.name
    if isinstance(t, StructType):
        return "S" + t.name
    if t.size is None:
        return "list_" + _mangle(t.element)
    return f"arr{t.size}_" + _mangle(t.element)

def _list_name(t: ArrayType) -> str:
    return "wren_" + _mangle(t)

def _decl(t: Type, name: str) -> str:
    if isinstance(t, PrimitiveType):
        return f"{PRIMITIVES[t.name].c_type} {name}"
    if isinstance(t, StructType):
        return f"{t.name} {name}"
    if t.size is None:
        return f"{_list_name(t)} {name}"
    inner = f"({name})" if name.startswith("*") else name
    return _decl(t.element, f"{inner}[{t.size}]")

def _lists_in(t: Type, out: dict[str, ArrayType]) -> None:
    if isinstance(t, ArrayType):
        _lists_in(t.element, out)
        if t.size is None:
            out.setdefault(_mangle(t), t)

def _min_size(t: Type, structs: dict[str, Struct]) -> int:
    if isinstance(t, PrimitiveType):
        size = PRIMITIVES[t.name].size
        return 4 if size is None else size
    if isinstance(t, StructType):
        return sum(_min_size(f.type, structs) for f in structs[t.name].fields)
    return 4 if t.size is None else t.size * _min_size(t.element, structs)

def _block(lines: list[str]) -> list[str]:
    return ["    " + line for line in lines]

def _encode_lines(t: Type, expr: str, depth: int) -> list[str]:
    if isinstance(t, PrimitiveType):
        fn = "bytes" if t.name in ("bytes", "string") else t.name
        return [f"wren_write_{fn}(_w, {expr});"]
    if isinstance(t, StructType):
        return [f"{t.name}_encode(_w, &{expr});"]
    i = f"_i{depth}"
    if t.size is None:
        head = [f"wren_write_u32(_w, {expr}.len);"]
        count, items = f"{expr}.len", f"{expr}.items"
    else:
        head, count, items = [], str(t.size), expr
    return head + [
        f"for (uint32_t {i} = 0; {i} < {count}; {i}++) {{",
        *_block(_encode_lines(t.element, f"{items}[{i}]", depth + 1)),
        "}",
    ]

def _decode_lines(t: Type, expr: str, depth: int,
                  structs: dict[str, Struct]) -> list[str]:
    if isinstance(t, PrimitiveType):
        fn = "bytes" if t.name in ("bytes", "string") else t.name
        return [f"wren_read_{fn}(_r, &{expr});"]
    if isinstance(t, StructType):
        return [f"{t.name}_decode(_r, _a, &{expr});"]
    i = f"_i{depth}"
    if t.size is None:
        head = [
            f"wren_read_count(_r, {_min_size(t.element, structs)}, &{expr}.len);",
            f"{expr}.items = wren_read_alloc(_r, _a, {expr}.len, sizeof(*{expr}.items));",
        ]
        count, items = f"{expr}.len", f"{expr}.items"
    else:
        head, count, items = [], str(t.size), expr
    return head + [
        f"for (uint32_t {i} = 0; _r->ok && {i} < {count}; {i}++) {{",
        *_block(_decode_lines(t.element, f"{items}[{i}]", depth + 1, structs)),
        "}",
    ]

def _emit_lists(types, emitted: set[str]) -> list[str]:
    needed: dict[str, ArrayType] = {}
    for t in types:
        _lists_in(t, needed)
    lines = []
    for key, t in needed.items():
        if key in emitted:
            continue
        emitted.add(key)
        lines += ["", "typedef struct {", "    uint32_t len;",
                  f"    {_decl(t.element, '*items')};",
                  f"}} {_list_name(t)};"]
    return lines

def _struct_typedef(s: Struct) -> list[str]:
    body = [_decl(f.type, f.name) + ";" for f in s.fields]
    if not body:
        body = ["char _unused;  /* ISO C forbids empty structs */"]
    return [f"typedef struct {s.name} {{", *_block(body), f"}} {s.name};"]

def _struct_prototypes(s: Struct) -> list[str]:
    return [
        f"void {s.name}_encode(wren_writer_t *_w, const {s.name} *_v);",
        f"void {s.name}_decode(wren_reader_t *_r, wren_arena_t *_a, {s.name} *_out);",
    ]

def _struct_functions(s: Struct, structs: dict[str, Struct]) -> list[str]:
    enc = [line for f in s.fields
           for line in _encode_lines(f.type, f"_v->{f.name}", 0)]
    dec = [line for f in s.fields
           for line in _decode_lines(f.type, f"_out->{f.name}", 0, structs)]
    enc_unused = [] if s.fields else ["(void)_w;", "(void)_v;"]
    dec_unused = ["(void)_a;"] + ([] if s.fields else ["(void)_r;", "(void)_out;"])
    return [
        f"void {s.name}_encode(wren_writer_t *_w, const {s.name} *_v) {{",
        *_block(enc_unused + enc),
        "}",
        "",
        f"void {s.name}_decode(wren_reader_t *_r, wren_arena_t *_a, {s.name} *_out) {{",
        *_block(dec_unused + dec),
        "}",
    ]

def _outputs(m: Method) -> list[tuple[str, Type]]:
    if m.returns is None:
        return []
    if isinstance(m.returns, TupleReturn):
        return [(f.name, f.type) for f in m.returns.fields]
    return [("result", m.returns)]

def _method_types(m: Method) -> list[Type]:
    return [a.type for a in m.args] + [t for _, t in _outputs(m)]

def _by_pointer(t: Type) -> bool:
    return isinstance(t, StructType) or (isinstance(t, ArrayType) and t.size is None)

def _arg_param(t: Type) -> str:
    if _by_pointer(t):
        return "const " + _decl(t, "*")
    if isinstance(t, ArrayType):
        return "const " + _decl(t, "").rstrip()
    return _decl(t, "").rstrip()

def _handler_member(m: Method) -> list[str]:
    params = ["wren_call_t *"]
    params += [f"{_arg_param(a.type)} /* {a.name} */" for a in m.args]
    params += [f"{_decl(t, '*')} /* {n} */" for n, t in _outputs(m)]
    head = f"int (*{m.name})("
    pad = " " * len(head)
    return [(head if i == 0 else pad) + p + (");" if i == len(params) - 1 else ",")
            for i, p in enumerate(params)]

def _service_header(svc: Service) -> list[str]:
    n = svc.name
    members = [line for m in svc.methods for line in _handler_member(m)]
    return [
        "",
        "/*",
        f" * Handlers for service {n}. Each returns 0 after filling its outputs,",
        " * and the reply is encoded and sent for it. To fail, call",
        " * wren_call_reply_error() and return nonzero; returning nonzero without",
        " * replying sends a generic error. Arguments, and memory from",
        " * wren_call_arena(), stay valid until the handler returns.",
        " */",
        f"typedef struct {n}_handlers {{",
        f"    void *_ctx;  /* set by {n}_register; read it with {n}_ctx() */",
        *_block(members),
        f"}} {n}_handlers;",
        "",
        f"/** Register every non-NULL handler in @_h under its method ID. @_h must",
        " *  outlive the server. */",
        f"int {n}_register(wren_server_t *_s, {n}_handlers *_h, void *_ctx);",
        "",
        f"/** The context passed to {n}_register, from inside a handler. */",
        f"void *{n}_ctx(wren_call_t *_call);",
    ]

def _shim(svc: Service, m: Method, structs: dict[str, Struct]) -> list[str]:
    body = [f"{svc.name}_handlers *_h = wren_call_ctx(_call);"]
    if m.args:
        body += ["struct {",
                 *_block([_decl(a.type, a.name) + ";" for a in m.args]),
                 "} _args;"]
    outs = _outputs(m)
    if outs:
        body += ["struct {",
                 *_block([_decl(t, name) + ";" for name, t in outs]),
                 "} _out;",
                 "memset(&_out, 0, sizeof _out);  /* never send stack garbage */"]
    body += [
        "const char *_data;",
        "size_t _len;",
        "wren_call_payload(_call, &_data, &_len);",
        "wren_reader_t _rd;",
        "wren_reader_t *_r = &_rd;",
        "wren_arena_t *_a = wren_call_arena(_call);",
        "(void)_a;",
        "wren_reader_init(_r, _data, _len);",
    ]
    for a in m.args:
        body += _decode_lines(a.type, f"_args.{a.name}", 0, structs)
    body += [
        "if (!wren_reader_done(_r)) {",
        "    wren_call_reply_error(_call, WREN_ERR_BAD_ARGS,",
        "                          \"arguments do not match the method's schema\");",
        "    return;",
        "}",
    ]
    call_args = ["_call"]
    call_args += [("&" if _by_pointer(a.type) else "") + f"_args.{a.name}" for a in m.args]
    call_args += [f"&_out.{name}" for name, _ in outs]
    body += [
        f"int _rc = _h->{m.name}({', '.join(call_args)});",
        "if (_rc != 0) {",
        "    if (!wren_call_replied(_call))",
        "        wren_call_reply_error(_call, 0, \"handler failed\");",
        "    return;",
        "}",
        "wren_writer_t _wr;",
        "wren_writer_t *_w = &_wr;",
        "wren_writer_init(_w);",
    ]
    for name, t in outs:
        body += _encode_lines(t, f"_out.{name}", 0)
    body += [
        "if (_w->ok)",
        "    wren_call_reply_raw(_call, _w->buf, _w->len);",
        "else",
        "    wren_call_reply_error(_call, 0, \"out of memory encoding reply\");",
        "wren_writer_free(_w);",
    ]
    return [f"static void {svc.name}_{m.name}_shim(wren_call_t *_call) {{",
            *_block(body), "}"]

def _service_source(svc: Service, structs: dict[str, Struct]) -> list[str]:
    n = svc.name
    lines = []
    for m in svc.methods:
        lines += ["", *_shim(svc, m, structs)]
    regs = [f"if (_h->{m.name} && wren_server_register_ctx("
            f"_s, {m.method_id}, {n}_{m.name}_shim, _h) < 0)\n        return -1;"
            for m in svc.methods]
    lines += [
        "",
        f"int {n}_register(wren_server_t *_s, {n}_handlers *_h, void *_ctx) {{",
        "    _h->_ctx = _ctx;",
        *_block(regs),
        "    return 0;",
        "}",
        "",
        f"void *{n}_ctx(wren_call_t *_call) {{",
        f"    return (({n}_handlers *)wren_call_ctx(_call))->_ctx;",
        "}",
    ]
    return lines

def emit_c(schema: Schema, name: str) -> tuple[str, str]:
    structs = {s.name: s for s in schema.structs}

    h = [_BANNER, "#pragma once", "",
         "#include <stdbool.h>", "#include <stdint.h>", "",
         '#include "wren/codec.h"']
    if schema.services:
        h.append('#include "wren/server.h"')
    emitted: set[str] = set()
    for s in schema.structs:
        h += _emit_lists((f.type for f in s.fields), emitted)
        h += ["", *_struct_typedef(s), "", *_struct_prototypes(s)]
    for svc in schema.services:
        h += _emit_lists((t for m in svc.methods for t in _method_types(m)), emitted)
        h += _service_header(svc)

    c = [_BANNER, "#include <string.h>", "", f'#include "{name}.h"']
    for s in schema.structs:
        c += ["", *_struct_functions(s, structs)]
    for svc in schema.services:
        c += _service_source(svc, structs)

    return "\n".join(h) + "\n", "\n".join(c) + "\n"