"""Python emitter that turns validated wren schema into python source code"""

from __future__ import annotations

from .ast import (
    ArrayType, PrimitiveType, Schema, Service, Struct, StructType, 
    TupleReturn, Type,
)
from .typemap import PRIMITIVES

_HEADER = """\
# Generated by wrengen. Do not edit.
from __future__ import annotations

import dataclasses as _dataclasses

import wren.codec as _codec

_len = len
_range = range
_ValueError = ValueError
"""

def _py_type(t: Type) -> str:
    if isinstance(t, PrimitiveType):
        return PRIMITIVES[t.name].py_type
    if isinstance(t, StructType):
        return t.name
    return f"list[{_py_type(t.element)}]"

def _encode_lines(t: Type, expr: str, depth: int) -> list[str]:
    if isinstance(t, PrimitiveType):
        if t.name == "bytes":
            return [f"_w.put_bytes({expr})"]
        if t.name == "string":
            return [f"_w.put_string({expr})"]
        return [f'_w.put("{PRIMITIVES[t.name].py_fmt}", {expr})']
    if isinstance(t, StructType):
        return [f"{expr}._encode(_w)"]

    # arraytype
    item = f"_e{depth}"
    if t.size is None:
        lines = [f'_w.put("I", _len({expr}))']
    else:
        lines = [
            f"if _len({expr}) != {t.size}:",
            f'    raise _ValueError(f"expected {t.size} elements, got {{_len({expr})}}")',
        ]
    lines.append(f"for {item} in {expr}:")
    lines += ["    " + line for line in _encode_lines(t.element, item, depth + 1)]
    return lines

def _decode_expr(t: Type) -> str:
    if isinstance(t, PrimitiveType):
        if t.name == "bytes":
            return "_r.get_bytes()"
        if t.name == "string":
            return "_r.get_string()"
        return f'_r.get("{PRIMITIVES[t.name].py_fmt}")'
    if isinstance(t, StructType):
        return f"{t.name}._decode(_r)"

    count = '_r.get("I")' if t.size is None else str(t.size)
    return f"[{_decode_expr(t.element)} for _ in _range({count})]"

def _emit_struct(s: Struct) -> list[str]:
    lines = ["@_dataclasses.dataclass", f"class {s.name}:"]
    lines += [f"    {f.name}: {_py_type(f.type)}" for f in s.fields]

    lines += ["", "    def _encode(_self, _w: _codec.Writer) -> None:"]
    body = [line for f in s.fields
            for line in _encode_lines(f.type, f"_self.{f.name}", 0)]
    lines += ["        " + line for line in body] or ["        pass"]

    lines += ["", "    @classmethod",
              f"    def _decode(_cls, _r: _codec.Reader) -> {s.name}:"]
    if s.fields:
        lines.append("        return _cls(")
        lines += [f"            {_decode_expr(f.type)}," for f in s.fields]
        lines.append("        )")
    else:
        lines.append("        return _cls()")

    lines += [
        "",
        "    def encode(_self) -> bytes:",
        "        _w = _codec.Writer()",
        "        _self._encode(_w)",
        "        return _w.getvalue()",
        "",
        "    @classmethod",
        f"    def decode(_cls, _data: bytes) -> {s.name}:",
        "        _r = _codec.Reader(_data)",
        "        _value = _cls._decode(_r)",
        "        _r.expect_end()",
        "        return _value",
    ]
    return lines

def _return_type(returns: Type | TupleReturn | None) -> str:
    if returns is None:
        return "None"
    if isinstance(returns, TupleReturn):
        return f"tuple[{', '.join(_py_type(a.type) for a in returns.fields)}]"
    return _py_type(returns)

def _return_expr(returns: Type | TupleReturn) -> str:
    if isinstance(returns, TupleReturn):
        return f"({', '.join(_decode_expr(a.type) for a in returns.fields)},)"
    return _decode_expr(returns)

def _emit_service(svc: Service) -> list[str]:
    lines = [
        f"class {svc.name}:",
        f'    """Typed client for service {svc.name}. Wraps a wren.Client."""',
        "",
        "    def __init__(_self, _client) -> None:",
        "        _self._client = _client",
        "",
        "    def close(_self) -> None:",
        "        _self._client.close()",
        "",
        f"    def __enter__(_self) -> {svc.name}:",
        "        return _self",
        "",
        "    def __exit__(_self, *_exc) -> None:",
        "        _self.close()",
    ]
    for m in svc.methods:
        params = "".join(f", {a.name}: {_py_type(a.type)}" for a in m.args)
        lines += [
            "",
            f"    def {m.name}(_self{params}) -> {_return_type(m.returns)}:",
            "        _w = _codec.Writer()",
        ]
        body = [line for a in m.args
                for line in _encode_lines(a.type, a.name, 0)]
        lines += ["        " + line for line in body]
        lines.append(f"        _r = _codec.Reader("
                     f"_self._client.call({m.method_id}, _w.getvalue()))")
        if m.returns is None:
            lines.append("        _r.expect_end()")
        else:
            lines += [
                f"        _value = {_return_expr(m.returns)}",
                "        _r.expect_end()",
                "        return _value",
            ]
    return lines

def emit_python(schema: Schema) -> str:
    parts = [_HEADER]
    for s in schema.structs:
        parts.append("\n\n" + "\n".join(_emit_struct(s)) + "\n")
    for svc in schema.services:
        parts.append("\n\n" + "\n".join(_emit_service(svc)) + "\n")
    return "".join(parts)